-- migrate:up
CREATE TABLE users (
  id VARCHAR(64) NOT NULL PRIMARY KEY,
  username VARCHAR(200) UNIQUE NOT NULL,
  email VARCHAR(200) UNIQUE NOT NULL,
  avatar VARCHAR(255) DEFAULT NULL,
  password VARCHAR(200) NOT NULL,
  is_super BOOLEAN DEFAULT FALSE,
  is_deleted BOOLEAN DEFAULT FALSE,
  deleted_at TIMESTAMP DEFAULT NULL,
  created_at TIMESTAMP DEFAULT NULL,
  updated_at TIMESTAMP DEFAULT NULL
);

-- migrate:down
DROP TABLE users;
