// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Document struct {
	ID        string
	ParentID  pgtype.Text
	ProjectID pgtype.Text
	PreDocID  pgtype.Text
	Name      string
	IsFolder  pgtype.Bool
	IsDeleted pgtype.Bool
	CreatedBy pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedBy pgtype.Text
	UpdatedAt pgtype.Timestamp
}

type Project struct {
	ID          string
	Name        string
	Description pgtype.Text
	IsDeleted   pgtype.Bool
	IsPublic    pgtype.Bool
	CreatedBy   pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedBy   pgtype.Text
	UpdatedAt   pgtype.Timestamp
}

type User struct {
	ID        string
	Username  string
	Email     string
	Avatar    pgtype.Text
	Password  string
	IsSuper   pgtype.Bool
	IsDeleted pgtype.Bool
	DeletedAt pgtype.Timestamp
	DeletedBy pgtype.Text
	CreatedBy pgtype.Text
	CreatedAt pgtype.Timestamp
	UpdatedBy pgtype.Text
	UpdatedAt pgtype.Timestamp
}
