// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        string
	Username  string
	Email     string
	Avatar    pgtype.Text
	Password  string
	IsSuper   pgtype.Bool
	IsDeleted pgtype.Bool
	DeletedAt pgtype.Timestamp
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
	CreatedBy pgtype.Text
	UpdatedBy pgtype.Text
	DeletedBy pgtype.Text
}
